"""empty message

Revision ID: 231baef6ed8c
Revises: 11cfc69fd369
Create Date: 2023-05-23 00:17:38.643626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231baef6ed8c'
down_revision = '11cfc69fd369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
