"""empty message

Revision ID: 299edd95d109
Revises: b3c8ef9c48a0
Create Date: 2023-05-15 00:15:46.066271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299edd95d109'
down_revision = 'b3c8ef9c48a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GenreAssignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GenreAssignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
