"""empty message

Revision ID: 913851daf645
Revises: 231baef6ed8c
Create Date: 2023-05-23 01:17:18.829045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913851daf645'
down_revision = '231baef6ed8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
