"""empty message

Revision ID: 9304eed171ba
Revises: c35bccb182a6
Create Date: 2023-05-21 18:02:05.901500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9304eed171ba'
down_revision = 'c35bccb182a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
