"""empty message

Revision ID: b3c8ef9c48a0
Revises: 
Create Date: 2023-05-15 00:14:26.086576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c8ef9c48a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GenreAssignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('ALTERNATIVE', 'BLUES', 'CLASSICAL', 'COUNTY', 'ELECTRONIC', 'FOLK', 'FUNK', 'HIPHOP', 'HEAVYMETAL', 'INSTRUMENTAL', 'JAZZ', 'MUSICAL', 'POP', 'PUNK', 'RANDB', 'REGGAE', 'ROCK_N_ROLL', 'SOUL', 'OTHER', name='genre'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('GenreAssignment')
    # ### end Alembic commands ###
